; SICP 2.5「汎用演算のシステム」を scheme13 で確認する。
;   2.5.1 汎用算術演算 / 2.5.2 異なる型のデータの統合（型強制と型の塔）
;   2.5.3 例: 記号代数（多項式の算術）
;
; 処理系側で問われるのは
;   - 型の塔（整数→有理数→実数→複素数）を Scheme 側で組めること。
;     **scheme13 自身は有理数も複素数も持たない**（§2.3 で凍結）ので、
;     この節はまさに「無い数を、対とタグで自分で作る」章になる
;   - 係数がまた多項式であるような再帰的なデータに、同じ総称手続きが効くこと

(define ng-count 0)
(define total-count 0)
(define (check label expr expected)
  (set! total-count (+ total-count 1))
  (if (equal? expr expected)
      (begin (display "ok   ") (display label) (newline))
      (begin (set! ng-count (+ ng-count 1))
             (display "NG   ") (display label)
             (display "  got=") (write expr)
             (display " want=") (write expected) (newline))))
(define (check~ label expr expected eps)
  (set! total-count (+ total-count 1))
  (if (< (abs (- expr expected)) eps)
      (begin (display "ok   ") (display label) (newline))
      (begin (set! ng-count (+ ng-count 1))
             (display "NG   ") (display label)
             (display "  got=") (write expr)
             (display " want=") (write expected) (newline))))
(define (summary name)
  (display "=== ") (display name)
  (display "  total: ") (display total-count)
  (display "  NG: ") (display ng-count) (display " ===") (newline))

(define (square x) (* x x))

; --- 操作と型の表 ---
(define op-table '())
(define (put op type item) (set! op-table (cons (list op type item) op-table)))
(define (get op type)
  (define (loop rows)
    (cond ((null? rows) #f)
          ((and (equal? (car (car rows)) op) (equal? (cadr (car rows)) type)) (caddr (car rows)))
          (else (loop (cdr rows)))))
  (loop op-table))
(define coercion-table '())
(define (put-coercion from to proc) (set! coercion-table (cons (list from to proc) coercion-table)))
(define (get-coercion from to)
  (define (loop rows)
    (cond ((null? rows) #f)
          ((and (eq? (car (car rows)) from) (eq? (cadr (car rows)) to)) (caddr (car rows)))
          (else (loop (cdr rows)))))
  (loop coercion-table))

; タグ。数だけは裸のまま持たせる（書籍の演習 2.78 の扱い）。
(define (attach-tag type-tag contents)
  (if (eq? type-tag 'scheme-number) contents (cons type-tag contents)))
(define (type-tag datum)
  (cond ((number? datum) 'scheme-number)
        ((pair? datum) (car datum))
        (else (error "Bad tagged datum -- TYPE-TAG" datum))))
(define (contents datum)
  (cond ((number? datum) datum)
        ((pair? datum) (cdr datum))
        (else (error "Bad tagged datum -- CONTENTS" datum))))

; --- 2.5.1 汎用算術 ---
(define (install-scheme-number-package)
  (define (tag x) (attach-tag 'scheme-number x))
  (put 'add '(scheme-number scheme-number) (lambda (x y) (tag (+ x y))))
  (put 'sub '(scheme-number scheme-number) (lambda (x y) (tag (- x y))))
  (put 'mul '(scheme-number scheme-number) (lambda (x y) (tag (* x y))))
  (put 'div '(scheme-number scheme-number) (lambda (x y) (tag (/ x y))))
  (put 'equ? '(scheme-number scheme-number) =)
  (put '=zero? '(scheme-number) (lambda (x) (= x 0)))
  (put 'make 'scheme-number (lambda (x) (tag x)))
  'done)

(define (install-rational-package)
  (define (numer x) (car x))
  (define (denom x) (cdr x))
  (define (make-rat n d)
    (let ((g (gcd n d)) (s (if (< d 0) -1 1)))
      (cons (quotient (* s n) g) (quotient (* s d) g))))
  (define (add-rat x y) (make-rat (+ (* (numer x) (denom y)) (* (numer y) (denom x)))
                                  (* (denom x) (denom y))))
  (define (sub-rat x y) (make-rat (- (* (numer x) (denom y)) (* (numer y) (denom x)))
                                  (* (denom x) (denom y))))
  (define (mul-rat x y) (make-rat (* (numer x) (numer y)) (* (denom x) (denom y))))
  (define (div-rat x y) (make-rat (* (numer x) (denom y)) (* (denom x) (numer y))))
  (define (tag x) (attach-tag 'rational x))
  (put 'add '(rational rational) (lambda (x y) (tag (add-rat x y))))
  (put 'sub '(rational rational) (lambda (x y) (tag (sub-rat x y))))
  (put 'mul '(rational rational) (lambda (x y) (tag (mul-rat x y))))
  (put 'div '(rational rational) (lambda (x y) (tag (div-rat x y))))
  (put 'equ? '(rational rational)
       (lambda (x y) (and (= (numer x) (numer y)) (= (denom x) (denom y)))))
  (put '=zero? '(rational) (lambda (x) (= (numer x) 0)))
  (put 'numer '(rational) numer)
  (put 'denom '(rational) denom)
  (put 'make 'rational (lambda (n d) (tag (make-rat n d))))
  'done)

(define (install-complex-package)
  (define (make-z x y) (cons x y))
  (define (real-p z) (car z))
  (define (imag-p z) (cdr z))
  (define (magnitude z) (sqrt (+ (square (real-p z)) (square (imag-p z)))))
  (define (angle z) (atan (imag-p z) (real-p z)))
  (define (add-z z1 z2) (make-z (+ (real-p z1) (real-p z2)) (+ (imag-p z1) (imag-p z2))))
  (define (sub-z z1 z2) (make-z (- (real-p z1) (real-p z2)) (- (imag-p z1) (imag-p z2))))
  (define (mul-z z1 z2) (make-z (- (* (real-p z1) (real-p z2)) (* (imag-p z1) (imag-p z2)))
                                (+ (* (real-p z1) (imag-p z2)) (* (imag-p z1) (real-p z2)))))
  (define (div-z z1 z2)
    (let ((d (+ (square (real-p z2)) (square (imag-p z2)))))
      (make-z (/ (+ (* (real-p z1) (real-p z2)) (* (imag-p z1) (imag-p z2))) d)
              (/ (- (* (imag-p z1) (real-p z2)) (* (real-p z1) (imag-p z2))) d))))
  (define (tag z) (attach-tag 'complex z))
  (put 'add '(complex complex) (lambda (z1 z2) (tag (add-z z1 z2))))
  (put 'sub '(complex complex) (lambda (z1 z2) (tag (sub-z z1 z2))))
  (put 'mul '(complex complex) (lambda (z1 z2) (tag (mul-z z1 z2))))
  (put 'div '(complex complex) (lambda (z1 z2) (tag (div-z z1 z2))))
  (put 'equ? '(complex complex)
       (lambda (z1 z2) (and (= (real-p z1) (real-p z2)) (= (imag-p z1) (imag-p z2)))))
  (put '=zero? '(complex) (lambda (z) (and (= (real-p z) 0) (= (imag-p z) 0))))
  (put 'real-part '(complex) real-p)
  (put 'imag-part '(complex) imag-p)
  (put 'magnitude '(complex) magnitude)
  (put 'angle '(complex) angle)
  (put 'make-from-real-imag 'complex (lambda (x y) (tag (make-z x y))))
  'done)

(check "数のパッケージ"   (install-scheme-number-package) 'done)
(check "有理数のパッケージ" (install-rational-package) 'done)
(check "複素数のパッケージ" (install-complex-package) 'done)

(define (apply-generic op . args)
  (let ((type-tags (map type-tag args)))
    (let ((proc (get op type-tags)))
      (if proc
          (apply proc (map contents args))
          ; 直接の方法が無ければ型強制を試す（2.5.2）
          (if (= (length args) 2)
              (let ((t1 (car type-tags)) (t2 (cadr type-tags))
                    (a1 (car args)) (a2 (cadr args)))
                (let ((t1->t2 (get-coercion t1 t2)) (t2->t1 (get-coercion t2 t1)))
                  (cond (t1->t2 (apply-generic op (t1->t2 a1) a2))
                        (t2->t1 (apply-generic op a1 (t2->t1 a2)))
                        (else (error "No method for these types" (list op type-tags))))))
              (error "No method for these types" (list op type-tags)))))))

(define (add x y) (apply-generic 'add x y))
(define (sub x y) (apply-generic 'sub x y))
(define (mul x y) (apply-generic 'mul x y))
(define (div x y) (apply-generic 'div x y))
(define (equ? x y) (apply-generic 'equ? x y))
(define (=zero? x) (apply-generic '=zero? x))
(define (make-scheme-number n) ((get 'make 'scheme-number) n))
(define (make-rational n d) ((get 'make 'rational) n d))
(define (make-complex-from-real-imag x y) ((get 'make-from-real-imag 'complex) x y))
(define (real-part z) (apply-generic 'real-part z))
(define (imag-part z) (apply-generic 'imag-part z))
(define (magnitude z) (apply-generic 'magnitude z))
(define (numer q) (apply-generic 'numer q))
(define (denom q) (apply-generic 'denom q))

(define n3 (make-scheme-number 3))
(define n4 (make-scheme-number 4))
(define q12 (make-rational 1 2))
(define q13 (make-rational 1 3))
(define z34 (make-complex-from-real-imag 3 4))
(define z10 (make-complex-from-real-imag 1 0))

(check "数どうしの加算"     (add n3 n4) 7)
(check "数どうしの乗算"     (mul n3 n4) 12)
(check "有理数の加算"       (add q12 q13) (make-rational 5 6))
(check "有理数の乗算"       (mul q12 q13) (make-rational 1 6))
(check "有理数の除算"       (div q12 q13) (make-rational 3 2))
(check "有理数は約分される" (add q13 q13) (make-rational 2 3))
(check "複素数の加算"       (add z34 z34) (make-complex-from-real-imag 6 8))
(check "複素数の乗算"       (mul z34 z34) (make-complex-from-real-imag -7 24))
; 成分が正確な整数なので、sqrt(25) も正確な 5 で返る（実数にならない）。
; 2.4 では成分を 3.0/4.0 にしたので 5.0 だった。**正確さは値の一部**（決定85）。
(check "複素数の絶対値"     (magnitude z34) 5)
(check "成分が実数なら絶対値も実数"
       (magnitude (make-complex-from-real-imag 3.0 4.0)) 5.0)
; 演習 2.79 / 2.80
(check "equ? 数"        (equ? n3 (make-scheme-number 3)) #t)
(check "equ? 有理数"    (equ? (make-rational 2 4) q12) #t)
(check "equ? 複素数"    (equ? z34 (make-complex-from-real-imag 3 4)) #t)
(check "equ? 違う値"    (equ? q12 q13) #f)
(check "=zero? 数"      (=zero? (make-scheme-number 0)) #t)
(check "=zero? 有理数"  (=zero? (make-rational 0 5)) #t)
(check "=zero? 複素数"  (=zero? (make-complex-from-real-imag 0 0)) #t)
(check "=zero? 非零"    (=zero? z34) #f)

; --- 2.5.2 型強制 ---
(define (scheme-number->complex n) (make-complex-from-real-imag (contents n) 0))
(put-coercion 'scheme-number 'complex scheme-number->complex)
(check "数と複素数を足す"   (add n3 z34) (make-complex-from-real-imag 6 4))
(check "向きが逆でも足せる" (add z34 n3) (make-complex-from-real-imag 6 4))
(check "数と複素数を掛ける" (mul n3 z10) (make-complex-from-real-imag 3 0))

; 型の塔（演習 2.83〜2.84）: 整数 → 有理数 → 実数 → 複素数
(define (install-real-package)
  (define (tag x) (attach-tag 'real x))
  (put 'add '(real real) (lambda (x y) (tag (+ x y))))
  (put 'mul '(real real) (lambda (x y) (tag (* x y))))
  (put 'equ? '(real real) =)
  (put '=zero? '(real) (lambda (x) (= x 0.0)))
  (put 'make 'real (lambda (x) (tag (exact->inexact x))))
  'done)
(check "実数のパッケージ" (install-real-package) 'done)
(define (make-real x) ((get 'make 'real) x))

(define (raise-value x)
  (let ((t (type-tag x)))
    (cond ((eq? t 'scheme-number) (make-rational (contents x) 1))
          ((eq? t 'rational) (make-real (/ (exact->inexact (numer x)) (denom x))))
          ((eq? t 'real) (make-complex-from-real-imag (contents x) 0))
          (else (error "Cannot raise" t)))))
(check "整数を有理数へ上げる" (raise-value n3) (make-rational 3 1))
(check "有理数を実数へ上げる" (raise-value q12) (make-real 0.5))
(check "実数を複素数へ上げる" (raise-value (make-real 2.5))
                              (make-complex-from-real-imag 2.5 0))
(check "3段上げると複素数"
       (type-tag (raise-value (raise-value (raise-value n3)))) 'complex)
(check "塔を上っても値は保たれる"
       (real-part (raise-value (raise-value (raise-value n3)))) 3.0)

; 塔の高さで揃えてから演算する（演習 2.84 の apply-generic）
(define (level x)
  (let ((t (type-tag x)))
    (cond ((eq? t 'scheme-number) 0) ((eq? t 'rational) 1)
          ((eq? t 'real) 2) ((eq? t 'complex) 3) (else (error "Unknown type" t)))))
(define (raise-to x n) (if (= (level x) n) x (raise-to (raise-value x) n)))
(define (add-tower x y)
  (let ((n (max (level x) (level y))))
    (add (raise-to x n) (raise-to y n))))
(check "整数と有理数を足す"   (add-tower n3 q12) (make-rational 7 2))
(check "整数と実数を足す"     (add-tower n3 (make-real 0.5)) (make-real 3.5))
(check "有理数と複素数を足す" (add-tower q12 z34) (make-complex-from-real-imag 3.5 4))

; --- 2.5.3 記号代数: 多項式 ---
(define (install-polynomial-package)
  (define (make-poly variable term-list) (cons variable term-list))
  (define (variable p) (car p))
  (define (term-list p) (cdr p))
  (define (same-variable? v1 v2) (and (symbol? v1) (symbol? v2) (eq? v1 v2)))
  ; 疎な項リスト: ((次数 係数) ...) を次数の降順で
  (define (adjoin-term term term-list)
    (if (=zero? (coeff term)) term-list (cons term term-list)))
  (define (the-empty-termlist) '())
  (define (first-term term-list) (car term-list))
  (define (rest-terms term-list) (cdr term-list))
  (define (empty-termlist? term-list) (null? term-list))
  (define (make-term order coeff) (list order coeff))
  (define (order term) (car term))
  (define (coeff term) (cadr term))
  (define (add-terms L1 L2)
    (cond ((empty-termlist? L1) L2)
          ((empty-termlist? L2) L1)
          (else
           (let ((t1 (first-term L1)) (t2 (first-term L2)))
             (cond ((> (order t1) (order t2)) (adjoin-term t1 (add-terms (rest-terms L1) L2)))
                   ((< (order t1) (order t2)) (adjoin-term t2 (add-terms L1 (rest-terms L2))))
                   (else (adjoin-term (make-term (order t1) (add (coeff t1) (coeff t2)))
                                      (add-terms (rest-terms L1) (rest-terms L2)))))))))
  (define (mul-term-by-all-terms t1 L)
    (if (empty-termlist? L)
        (the-empty-termlist)
        (let ((t2 (first-term L)))
          (adjoin-term (make-term (+ (order t1) (order t2)) (mul (coeff t1) (coeff t2)))
                       (mul-term-by-all-terms t1 (rest-terms L))))))
  (define (mul-terms L1 L2)
    (if (empty-termlist? L1)
        (the-empty-termlist)
        (add-terms (mul-term-by-all-terms (first-term L1) L2)
                   (mul-terms (rest-terms L1) L2))))
  (define (add-poly p1 p2)
    (if (same-variable? (variable p1) (variable p2))
        (make-poly (variable p1) (add-terms (term-list p1) (term-list p2)))
        (error "Polys not in same var -- ADD-POLY" (list p1 p2))))
  (define (mul-poly p1 p2)
    (if (same-variable? (variable p1) (variable p2))
        (make-poly (variable p1) (mul-terms (term-list p1) (term-list p2)))
        (error "Polys not in same var -- MUL-POLY" (list p1 p2))))
  (define (tag p) (attach-tag 'polynomial p))
  (put 'add '(polynomial polynomial) (lambda (p1 p2) (tag (add-poly p1 p2))))
  (put 'mul '(polynomial polynomial) (lambda (p1 p2) (tag (mul-poly p1 p2))))
  (put '=zero? '(polynomial) (lambda (p) (null? (term-list p))))
  (put 'make 'polynomial (lambda (var terms) (tag (make-poly var terms))))
  'done)
(check "多項式のパッケージ" (install-polynomial-package) 'done)
(define (make-polynomial var terms) ((get 'make 'polynomial) var terms))

; x^2 + 3x + 5 と 2x + 1
(define pa (make-polynomial 'x '((2 1) (1 3) (0 5))))
(define pb (make-polynomial 'x '((1 2) (0 1))))
(check "多項式の和"
       (add pa pb) (make-polynomial 'x '((2 1) (1 5) (0 6))))
(check "多項式の積"
       (mul pa pb) (make-polynomial 'x '((3 2) (2 7) (1 13) (0 5))))
(check "=zero? は空の項リスト" (=zero? (make-polynomial 'x '())) #t)
(check "係数が消える項は落ちる"
       (add (make-polynomial 'x '((1 1))) (make-polynomial 'x '((1 -1))))
       (make-polynomial 'x '()))

; **係数がまた多項式でもよい。** 総称手続きが再帰的に効くことがこの節の眼目。
(define py (make-polynomial 'y '((1 1) (0 1))))         ; y + 1
(define pxy (make-polynomial 'x (list (list 1 py) (list 0 py))))  ; (y+1)x + (y+1)
(check "係数が多項式でも足せる"
       (add pxy pxy)
       (make-polynomial 'x (list (list 1 (make-polynomial 'y '((1 2) (0 2))))
                                 (list 0 (make-polynomial 'y '((1 2) (0 2)))))))
; 係数どうしの積は「y の多項式 × y の多項式」でなければならない。
; 定数 2 を裸の数で書くと `mul` が (polynomial scheme-number) になり、
; 型強制の表にその組が無いので落ちる。**これは書籍 2.5.2 が指摘している
; 「塔にならない型の関係」そのもの**で、処理系の問題ではない。
(check "係数が多項式でも掛けられる"
       (mul pxy (make-polynomial 'x (list (list 0 (make-polynomial 'y '((0 2)))))))
       (make-polynomial 'x (list (list 1 (make-polynomial 'y '((1 2) (0 2))))
                                 (list 0 (make-polynomial 'y '((1 2) (0 2)))))))
; 係数どうしの掛け算が、型強制ごしに動く（数×多項式は多項式の側に降りない）
(check "多項式の係数に有理数を使える"
       (add (make-polynomial 'x (list (list 0 (make-rational 1 2))))
            (make-polynomial 'x (list (list 0 (make-rational 1 3)))))
       (make-polynomial 'x (list (list 0 (make-rational 5 6)))))

(summary "SICP 2.5")
