; SICP 3.3.4「ディジタル回路のシミュレータ」と 3.3.5「制約の伝播」を
; scheme13 で確認する。
;
; 第3章で最も大きい2つのプログラムで、処理系としては総合試験になる。
;   - 局所状態を持つ物（線、接続子）を大量に作って繋ぐ
;   - 手続きを表に溜めて後で呼ぶ（行動リスト、議事日程）
;   - キュー（3.3.2）の上に議事日程を積む
;   - 制約は**向きを持たない**ので、同じ物が入力にも出力にもなる
;
; 書籍は結果を `display` で流すが、それでは主張にならないので、
; probe が記録を残す形にしてある。

(define ng-count 0)
(define total-count 0)
(define (check label expr expected)
  (set! total-count (+ total-count 1))
  (if (equal? expr expected)
      (begin (display "ok   ") (display label) (newline))
      (begin (set! ng-count (+ ng-count 1))
             (display "NG   ") (display label)
             (display "  got=") (write expr)
             (display " want=") (write expected) (newline))))
(define (summary name)
  (display "=== ") (display name)
  (display "  total: ") (display total-count)
  (display "  NG: ") (display ng-count) (display " ===") (newline))

; --- キュー（3.3.2。議事日程が使う）---
(define (front-ptr q) (car q))
(define (rear-ptr q) (cdr q))
(define (set-front-ptr! q x) (set-car! q x))
(define (set-rear-ptr! q x) (set-cdr! q x))
(define (make-queue) (cons '() '()))
(define (empty-queue? q) (null? (front-ptr q)))
(define (front-queue q)
  (if (empty-queue? q) (error "FRONT called with an empty queue" q) (car (front-ptr q))))
(define (insert-queue! q item)
  (let ((new (cons item '())))
    (if (empty-queue? q)
        (begin (set-front-ptr! q new) (set-rear-ptr! q new))
        (begin (set-cdr! (rear-ptr q) new) (set-rear-ptr! q new)))
    q))
(define (delete-queue! q)
  (if (empty-queue? q)
      (error "DELETE! called with an empty queue" q)
      (begin (set-front-ptr! q (cdr (front-ptr q)))
             (if (null? (front-ptr q)) (set-rear-ptr! q '()))
             q)))

; --- 議事日程（時刻つきのキューの並び）---
(define (make-time-segment time queue) (cons time queue))
(define (segment-time s) (car s))
(define (segment-queue s) (cdr s))
(define (make-agenda) (list 0))
(define (current-time agenda) (car agenda))
(define (set-current-time! agenda time) (set-car! agenda time))
(define (segments agenda) (cdr agenda))
(define (set-segments! agenda segs) (set-cdr! agenda segs))
(define (first-segment agenda) (car (segments agenda)))
(define (rest-segments agenda) (cdr (segments agenda)))
(define (empty-agenda? agenda) (null? (segments agenda)))

(define (add-to-agenda! time action agenda)
  (define (belongs-before? segs)
    (or (null? segs) (< time (segment-time (car segs)))))
  (define (make-new-time-segment)
    (let ((q (make-queue)))
      (insert-queue! q action)
      (make-time-segment time q)))
  (define (add-to-segments! segs)
    (if (= (segment-time (car segs)) time)
        (insert-queue! (segment-queue (car segs)) action)
        (let ((rest (cdr segs)))
          (if (belongs-before? rest)
              (set-cdr! segs (cons (make-new-time-segment) rest))
              (add-to-segments! rest)))))
  (let ((segs (segments agenda)))
    (if (belongs-before? segs)
        (set-segments! agenda (cons (make-new-time-segment) segs))
        (add-to-segments! segs))))

(define (remove-first-agenda-item! agenda)
  (let ((q (segment-queue (first-segment agenda))))
    (delete-queue! q)
    (if (empty-queue? q) (set-segments! agenda (rest-segments agenda)))))
(define (first-agenda-item agenda)
  (if (empty-agenda? agenda)
      (error "Agenda is empty -- FIRST-AGENDA-ITEM" agenda)
      (let ((first (first-segment agenda)))
        (set-current-time! agenda (segment-time first))
        (front-queue (segment-queue first)))))

(define the-agenda (make-agenda))
(define (after-delay delay action)
  (add-to-agenda! (+ delay (current-time the-agenda)) action the-agenda))
(define (propagate)
  (if (empty-agenda? the-agenda)
      'done
      (let ((first-item (first-agenda-item the-agenda)))
        (first-item)
        (remove-first-agenda-item! the-agenda)
        (propagate))))

; --- 線 ---
(define (call-each procedures)
  (if (null? procedures)
      'done
      (begin ((car procedures)) (call-each (cdr procedures)))))
(define (make-wire)
  (let ((signal-value 0) (action-procedures '()))
    (define (set-my-signal! new-value)
      (if (not (= signal-value new-value))
          (begin (set! signal-value new-value) (call-each action-procedures))
          'done))
    (define (accept-action-procedure! proc)
      (set! action-procedures (cons proc action-procedures))
      (proc))
    (lambda (m)
      (cond ((eq? m 'get-signal) signal-value)
            ((eq? m 'set-signal!) set-my-signal!)
            ((eq? m 'add-action!) accept-action-procedure!)
            (else (error "Unknown operation -- WIRE" m))))))
(define (get-signal wire) (wire 'get-signal))
(define (set-signal! wire new-value) ((wire 'set-signal!) new-value))
(define (add-action! wire action) ((wire 'add-action!) action))

; --- 素子 ---
(define inverter-delay 2)
(define and-gate-delay 3)
(define or-gate-delay 5)

(define (logical-not s)
  (cond ((= s 0) 1) ((= s 1) 0) (else (error "Invalid signal" s))))
(define (logical-and a b)
  (if (and (= a 1) (= b 1)) 1 0))
(define (logical-or a b)
  (if (or (= a 1) (= b 1)) 1 0))

(define (inverter input output)
  (define (invert-input)
    (let ((new-value (logical-not (get-signal input))))
      (after-delay inverter-delay (lambda () (set-signal! output new-value)))))
  (add-action! input invert-input)
  'ok)
(define (and-gate a1 a2 output)
  (define (and-action-procedure)
    (let ((new-value (logical-and (get-signal a1) (get-signal a2))))
      (after-delay and-gate-delay (lambda () (set-signal! output new-value)))))
  (add-action! a1 and-action-procedure)
  (add-action! a2 and-action-procedure)
  'ok)
(define (or-gate a1 a2 output)                    ; 演習 3.28
  (define (or-action-procedure)
    (let ((new-value (logical-or (get-signal a1) (get-signal a2))))
      (after-delay or-gate-delay (lambda () (set-signal! output new-value)))))
  (add-action! a1 or-action-procedure)
  (add-action! a2 or-action-procedure)
  'ok)

(check "not 0"  (logical-not 0) 1)
(check "and 1 1" (logical-and 1 1) 1)
(check "and 1 0" (logical-and 1 0) 0)
(check "or 0 1"  (logical-or 0 1) 1)
(check "or 0 0"  (logical-or 0 0) 0)

; 反転器だけの回路
(define in1 (make-wire))
(define out1 (make-wire))
(inverter in1 out1)
(propagate)
(check "初期状態: 0 の反転は 1" (get-signal out1) 1)
(set-signal! in1 1)
(check "伝播前は古いまま"       (get-signal out1) 1)
(propagate)
(check "伝播すると 0 になる"    (get-signal out1) 0)

; --- 半加算器と全加算器 ---
(define (half-adder a b s c)
  (let ((d (make-wire)) (e (make-wire)))
    (or-gate a b d)
    (and-gate a b c)
    (inverter c e)
    (and-gate d e s)
    'ok))
(define (full-adder a b c-in sum c-out)
  (let ((s (make-wire)) (c1 (make-wire)) (c2 (make-wire)))
    (half-adder b c-in s c1)
    (half-adder a s sum c2)
    (or-gate c1 c2 c-out)
    'ok))

(define (test-half-adder a-val b-val)
  (set! the-agenda (make-agenda))
  (let ((a (make-wire)) (b (make-wire)) (s (make-wire)) (c (make-wire)))
    (half-adder a b s c)
    (propagate)
    (set-signal! a a-val)
    (set-signal! b b-val)
    (propagate)
    (list (get-signal s) (get-signal c))))
(check "半加算器 0+0" (test-half-adder 0 0) '(0 0))
(check "半加算器 1+0" (test-half-adder 1 0) '(1 0))
(check "半加算器 0+1" (test-half-adder 0 1) '(1 0))
(check "半加算器 1+1" (test-half-adder 1 1) '(0 1))   ; 和 0、桁上がり 1

(define (test-full-adder a-val b-val cin-val)
  (set! the-agenda (make-agenda))
  (let ((a (make-wire)) (b (make-wire)) (cin (make-wire))
        (sum (make-wire)) (cout (make-wire)))
    (full-adder a b cin sum cout)
    (propagate)
    (set-signal! a a-val) (set-signal! b b-val) (set-signal! cin cin-val)
    (propagate)
    (list (get-signal sum) (get-signal cout))))
(check "全加算器 0+0+0" (test-full-adder 0 0 0) '(0 0))
(check "全加算器 1+0+0" (test-full-adder 1 0 0) '(1 0))
(check "全加算器 1+1+0" (test-full-adder 1 1 0) '(0 1))
(check "全加算器 1+1+1" (test-full-adder 1 1 1) '(1 1))
(check "全加算器 0+1+1" (test-full-adder 0 1 1) '(0 1))

; 8通りすべてが「和 = (a+b+cin) の下位ビット、桁上げ = 上位ビット」になる
(check "全加算器の真理値表"
       (map (lambda (bits)
              (let ((r (test-full-adder (car bits) (cadr bits) (caddr bits)))
                    (n (+ (car bits) (cadr bits) (caddr bits))))
                (equal? r (list (modulo n 2) (quotient n 2)))))
            '((0 0 0) (0 0 1) (0 1 0) (0 1 1) (1 0 0) (1 0 1) (1 1 0) (1 1 1)))
       '(#t #t #t #t #t #t #t #t))

; 議事日程そのものの性質: 時刻は単調に進み、最後は空になる
(set! the-agenda (make-agenda))
(define log '())
(add-to-agenda! 10 (lambda () (set! log (cons 10 log))) the-agenda)
(add-to-agenda! 5  (lambda () (set! log (cons 5 log))) the-agenda)
(add-to-agenda! 10 (lambda () (set! log (cons 'ten-b log))) the-agenda)
(add-to-agenda! 1  (lambda () (set! log (cons 1 log))) the-agenda)
(check "議事日程は時刻順、同時刻は入れた順" (begin (propagate) (reverse log))
       '(1 5 10 ten-b))
(check "走らせ切ると空になる" (empty-agenda? the-agenda) #t)
(check "時刻は最後の項目まで進む" (current-time the-agenda) 10)

; --- 3.3.5 制約の伝播 ---
(define (make-connector)
  (let ((value #f) (informant #f) (constraints '()))
    (define (set-my-value newval setter)
      (cond ((not (has-value? me))
             (set! value newval)
             (set! informant setter)
             (for-each-except setter inform-about-value constraints))
            ((not (= value newval))
             (error "Contradiction" (list value newval)))
            (else 'ignored)))
    (define (forget-my-value retractor)
      (if (eq? retractor informant)
          (begin (set! informant #f)
                 (for-each-except retractor inform-about-no-value constraints))
          'ignored))
    (define (connect new-constraint)
      (if (not (memq new-constraint constraints))
          (set! constraints (cons new-constraint constraints)))
      (if (has-value? me) (inform-about-value new-constraint))
      'done)
    (define (me request)
      (cond ((eq? request 'has-value?) (if informant #t #f))
            ((eq? request 'value) value)
            ((eq? request 'set-value!) set-my-value)
            ((eq? request 'forget) forget-my-value)
            ((eq? request 'connect) connect)
            (else (error "Unknown operation -- CONNECTOR" request))))
    me))
(define (for-each-except exception procedure lst)
  (define (loop items)
    (cond ((null? items) 'done)
          ((eq? (car items) exception) (loop (cdr items)))
          (else (procedure (car items)) (loop (cdr items)))))
  (loop lst))
(define (has-value? connector) (connector 'has-value?))
(define (get-value connector) (connector 'value))
(define (set-value! connector new-value informant)
  ((connector 'set-value!) new-value informant))
(define (forget-value! connector retractor) ((connector 'forget) retractor))
(define (connect connector new-constraint) ((connector 'connect) new-constraint))
(define (inform-about-value constraint) (constraint 'I-have-a-value))
(define (inform-about-no-value constraint) (constraint 'I-lost-my-value))

(define (adder a1 a2 sum)
  (define (process-new-value)
    (cond ((and (has-value? a1) (has-value? a2))
           (set-value! sum (+ (get-value a1) (get-value a2)) me))
          ((and (has-value? a1) (has-value? sum))
           (set-value! a2 (- (get-value sum) (get-value a1)) me))
          ((and (has-value? a2) (has-value? sum))
           (set-value! a1 (- (get-value sum) (get-value a2)) me))))
  (define (process-forget-value)
    (forget-value! sum me) (forget-value! a1 me) (forget-value! a2 me)
    (process-new-value))
  (define (me request)
    (cond ((eq? request 'I-have-a-value) (process-new-value))
          ((eq? request 'I-lost-my-value) (process-forget-value))
          (else (error "Unknown request -- ADDER" request))))
  (connect a1 me) (connect a2 me) (connect sum me)
  me)

(define (multiplier m1 m2 product)
  (define (process-new-value)
    (cond ((or (and (has-value? m1) (= (get-value m1) 0))
               (and (has-value? m2) (= (get-value m2) 0)))
           (set-value! product 0 me))
          ((and (has-value? m1) (has-value? m2))
           (set-value! product (* (get-value m1) (get-value m2)) me))
          ((and (has-value? product) (has-value? m1))
           (set-value! m2 (/ (get-value product) (get-value m1)) me))
          ((and (has-value? product) (has-value? m2))
           (set-value! m1 (/ (get-value product) (get-value m2)) me))))
  (define (process-forget-value)
    (forget-value! product me) (forget-value! m1 me) (forget-value! m2 me)
    (process-new-value))
  (define (me request)
    (cond ((eq? request 'I-have-a-value) (process-new-value))
          ((eq? request 'I-lost-my-value) (process-forget-value))
          (else (error "Unknown request -- MULTIPLIER" request))))
  (connect m1 me) (connect m2 me) (connect product me)
  me)

(define (constant value connector)
  (define (me request) (error "Unknown request -- CONSTANT" request))
  (connect connector me)
  (set-value! connector value me)
  me)

; probe は書籍では display するが、ここでは記録を残す
(define probe-log '())
(define (probe name connector)
  (define (print-probe value) (set! probe-log (cons (list name value) probe-log)))
  (define (process-new-value) (print-probe (get-value connector)))
  (define (process-forget-value) (print-probe 'forgotten))
  (define (me request)
    (cond ((eq? request 'I-have-a-value) (process-new-value))
          ((eq? request 'I-lost-my-value) (process-forget-value))
          (else (error "Unknown request -- PROBE" request))))
  (connect connector me)
  me)

; 9C = 5(F - 32)
(define (celsius-fahrenheit-converter c f)
  (let ((u (make-connector)) (v (make-connector))
        (w (make-connector)) (x (make-connector)) (y (make-connector)))
    (multiplier c w u)
    (multiplier v x u)
    (adder v y f)
    (constant 9 w)
    (constant 5 x)
    (constant 32 y)
    'ok))

(define C (make-connector))
(define F (make-connector))
(celsius-fahrenheit-converter C F)
(probe 'Celsius C)
(probe 'Fahrenheit F)

(check "最初はどちらも値を持たない" (list (has-value? C) (has-value? F)) '(#f #f))
(set-value! C 25 'user)
(check "C を決めると F が決まる"    (get-value F) 77)
(check "C は 25 のまま"             (get-value C) 25)
(check "probe が両方を記録した"     (reverse probe-log) '((Celsius 25) (Fahrenheit 77)))

; 逆向きにも計算できる（制約は向きを持たない）。先に C を忘れさせる
(set! probe-log '())
(forget-value! C 'user)
(check "忘れると両方が値を失う"     (list (has-value? C) (has-value? F)) '(#f #f))
(set-value! F 212 'user)
(check "F を決めると C が決まる"    (get-value C) 100)
(check "同じ網が両方向に使える"     (get-value F) 212)

; 矛盾は検出される（ここでは踏まない。踏むと止まるので、条件だけ見る）
(check "設定した本人以外は忘れさせられない"
       (begin (forget-value! C 'someone-else) (has-value? C)) #t)

; 定数は誰かが設定しないと変わらない
(define K (make-connector))
(constant 42 K)
(check "定数は最初から値を持つ" (get-value K) 42)

; 加算器だけの網でも、3つのうち2つ決まれば残りが決まる
(define p1 (make-connector))
(define p2 (make-connector))
(define ps (make-connector))
(adder p1 p2 ps)
(set-value! p1 3 'user)
(set-value! ps 10 'user)
(check "和から逆算する" (get-value p2) 7)
(set! probe-log '())
(forget-value! ps 'user)
(check "元を忘れれば逆算した値も消える" (has-value? p2) #f)
(check "残っている値はそのまま"         (get-value p1) 3)

; 乗算器: 0 が絡む場合は片方だけで決まる
(define m1 (make-connector))
(define m2 (make-connector))
(define mp (make-connector))
(multiplier m1 m2 mp)
(set-value! m1 0 'user)
(check "0 を掛ければ相手を知らなくても積は 0" (get-value mp) 0)

(summary "SICP 3.3（4〜5）")
